### ISSUE TITLE
Sympa 6.2.16 - Unsubscribe Does Not Work

### ISSUE THREAD

**Issue by bcchrisupp** [sympa-community/sympa#29]
I'm running Sympa 6.2.16 released in June(?) of this year, yet the information at https://www.sympa.org/manual_6.2/message-handling#unsubscription_url says to use the snippet
"To unsubscribe from this list, clink here: [% 'auto_signoff' | url_abs([list.name],{email=>user.email}) %]" 
In a footer yet, this does not result in a unsubscribe e-mail being sent. We had to use the older version of the snippet
"To unsubscribe from this list, clink here: [% wwsympa_url %]/auto_signoff/[% listname %]/[% user.escaped_email %]"
To get it to work as advertised.

**Comment by ikedas** [comment]
Hi,

Typo was fixed:
https://www.sympa.org/manual_6.2/message-handling?do=diff&rev2[]=1495594351

Thanks!

**Comment by bcchrisupp** [comment]
Hello,

Unfortunately, fixing the typo for the "listname" parameter didn't fix the problem. There is also a typo for the word "click" in the sample footer text that currently reads as "clink".

We still have to use the old footer of "To unsubscribe from this list, clink here: [% wwsympa_url %]/auto_signoff/[% listname %]/[% user.escaped_email %]" to get Sympa to accept the messages sent to the list by subscribers/moderators/etc. This older format of the footer generates a link that the user can click that takes them to a page saying that an unsubscribe e-mail has been sent for confirmation. 

If we try to use the new footer of "To unsubscribe from this list, clink here: [% 'auto_signoff' | url_abs([listname],{email=>user.email}) %]" and attempt to send a message as anyone who is not a listmaster, we get a message from Sympa saying that the message was rejected due to "Your message cannot be personalized.  Please check template syntax.". If a listmaster sends the message, there isn't any problem with Sympa processing the message and sending it out. This newer format of the footer generates a link that the user can click that takes them to the default Sympa splashpage, No unsubscribe e-mail gets sent for the user to use. 

We're using Sympa 6.2.16 which was migrated from 5.3.4 (old server to new server). I'm not sure if this is playing a part of the odd behaviour.

Feel free to click the two generated links below as this will only affect our test lists.

Old Generated URL:
https://list.bcchr.ca/sympa/auto_signoff/imit_test/darylcam%40hotmail.com

New Generated URL: 
https://list.bcchr.ca/sympa/auto_signoff/imit_test?email=darylcam%40hotmail.com

**Comment by ikedas** [comment]
Hi,
Reported bug seems to be fixed by PR #26.
https://github.com/sympa-community/sympa/pull/26/commits/21d2f9de8e11d43461544a16a63fcd550ecea028

Please check HEAD of sympa-6.2 branch on repository, or please use older notiation.

**Comment by bcchrisupp** [comment]
Fantastic. Thanks for following up and for all your hard work on this project!
