### ISSUE TITLE
In Riseup lists, can't update message header or footer 

### ISSUE THREAD

**Issue by FV77380** [sympa-community/sympa#356]
Hi, 
In the Riseup list management, I try to go to Admin/Customizing/Edit message header or footer. I make an update in the text and then click on the save button.
The update doesn't work and i get the message : "ERROR (savefile) - Unknown action".

How can we make an update ? The contact address is no longer valid and we need to change it.

Thank you.

**Comment by ikedas** [comment]
Hi @FV77380,

I guess administrator of Riseup possiblly customized Sympa on their site.  At first, could you please contact Riseup Support?

**Comment by xavierba** [comment]
I guess that's on RiseUp side. They probably disabled the use of savefile completely to avoid the arbitrary file creation security flaw that was fixed in recent version of Sympa.
https://sympa-community.github.io/security/2018-001.html

**Comment by ikedas** [comment]
[Security Advisory](https://sympa-community.github.io/security/2018-001.html) was updated.
@FV77380, please let Riseup Support know.

**Comment by FV77380** [comment]
Hi, 

 

Trying to update the footer, I still get the same error message. 

I will try again a bit later.

 

Thank you for your support, 

François.

 

 

 

> Message du 03/07/18 04:23
> De : "IKEDA Soji" 
> A : "sympa-community/sympa" 
> Copie à : "FV77380" , "Mention" 
> Objet : Re: [sympa-community/sympa] In Riseup lists, can't update message header or footer (#356)
> 
>
> Security Advisory was updated.
> @FV77380, please let Riseup Support know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sympa-community/sympa","title":"sympa-community/sympa","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sympa-community/sympa"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ikedas in #356: [Security Advisory](https://sympa-community.github.io/security/2018-001.html) was updated.\r\n@FV77380, please let Riseup Support know.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/sympa-community/sympa/issues/356#issuecomment-401993142"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/sympa-community/sympa/issues/356#issuecomment-401993142", "url": "https://github.com/sympa-community/sympa/issues/356#issuecomment-401993142", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [sympa-community/sympa] In Riseup lists, can't update message header or footer (#356)", "sections": [ { "text": "", "activityTitle": "**IKEDA Soji**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@ikedas", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sympa-community/sympa\",\n\"issueId\": 356,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sympa-community/sympa\",\n\"issueId\": 356\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/sympa-community/sympa/issues/356#issuecomment-401993142" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349780651\n}" } ], "themeColor": "26292E" } ]

**Comment by ikedas** [comment]
Stagnating issue. Close by now.
